### ISSUE TITLE
Hao Dian

### ISSUE THREAD

**Issue by alanjian85** [aokblast/moodle-grading-tool#1]
Do you have time to contribute to the development of CargOS recently?

**Comment by aokblast** [comment]
Still struggling on TA things. I need more time

**Comment by alanjian85** [comment]
> Still struggling on TA things. I need more time

Okay, but I still hope that you view the messages more frequently so that we can synchronize our recognition of the situation and the decision of code style more easily.

**Comment by alanjian85** [comment]
@aokblast I'm almost done implementing the features in the spec. We should thus have a meeting soon. I have some important issues to discuss.
